"""todo setup

Revision ID: 391449e845e0
Revises: bd8ee225532f
Create Date: 2025-02-06 16:20:11.898616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '391449e845e0'
down_revision: Union[str, None] = 'bd8ee225532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_id', table_name='books')
    op.drop_table('books')
    op.add_column('authors', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('authors', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('authors', 'bio')
    op.drop_column('authors', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('authors', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('authors', 'description')
    op.drop_column('authors', 'title')
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='books_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    # ### end Alembic commands ###
